- name: Complete the second part
  hosts: all
  become: true
  roles:
    - role: common
      become: false

    - role: crio

    - role: geerlingguy.docker

    - role: minikube

    - role: helm

    - role: deploy
      become: false
