# Caddy configuration
caddy_config: "{{ lookup('ansible.builtin.template', 'Caddyfile.j2') }}"
caddy_systemd_capabilities_enabled: true

# GitLab configuration
gitlab_domain: gitlab.ansible.skyload.info
gitlab_version: 16.0.1-ce.0
gitlab_redirect_http_to_https: false
gitlab_create_self_signed_cert: false
gitlab_time_zone: Europe/Moscow
gitlab_nginx_listen_port: 8081
gitlab_nginx_listen_https: false
gitlab_extra_settings:
  - prometheus_monitoring:
      - key: enable
        type: plain
        value: |
          false

# Prometheus configuration
prometheus_version: 2.44.0
prometheus_scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "{{ ansible_fqdn }}:9090"
  - job_name: node
    static_configs:
      - targets:
          - "{{ ansible_fqdn }}:9100"
  - job_name: systemd
    static_configs:
      - targets:
          - "{{ ansible_fqdn }}:9558"
