# GitLab configuration
gitlab_domain: gitlab.ansible.skyload.info
gitlab_version: 16.0.1-ce.0
gitlab_redirect_http_to_https: false
gitlab_create_self_signed_cert: false
gitlab_time_zone: Europe/Moscow
gitlab_nginx_listen_port: 8081
gitlab_nginx_listen_https: false
