# CRI-O configuration
crio_version: "1.27"
crictl_version: 1.27.0

# Docker configuration
docker_install_compose: false
docker_users:
  - "{{ ansible_user }}"

# Helm configuration
helm_version: v3.12.0
helm_diff_version: v3.8.0
