- name: Install cert-manager operator
  kubernetes.core.k8s:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: cert-manager
    namespace: operators
    resource_definition:
      spec:
        channel: stable
        name: cert-manager
        source: operatorhubio-catalog
        sourceNamespace: olm

- name: Wait until cert-manager operator is up
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: operators
    label_selectors:
      - app.kubernetes.io/name=cert-manager
  register: cert_manager_pod_list
  until: cert_manager_pod_list | json_query('resources[*].status.phase') | unique == ["Running"]
  retries: 12
  delay: 10

- name: Create Let's Encrypt staging cluster issuer
  kubernetes.core.k8s:
    api_version: cert-manager.io/v1
    kind: ClusterIssuer
    name: letsencrypt-staging
    resource_definition:
      spec:
        acme:
          email: admin@skyload.info
          server: https://acme-staging-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: letsencrypt-staging
          solvers:
            - http01:
                ingress:
                  ingressClassName: nginx

- name: Create Let's Encrypt production cluster issuer
  kubernetes.core.k8s:
    api_version: cert-manager.io/v1
    kind: ClusterIssuer
    name: letsencrypt-production
    resource_definition:
      spec:
        acme:
          email: admin@skyload.info
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: letsencrypt-production
          solvers:
            - http01:
                ingress:
                  ingressClassName: nginx
