- name: Create gitlab-system namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: gitlab-system

- name: Create GitLab OperatorGroup
  kubernetes.core.k8s:
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    name: operatorgroup
    namespace: gitlab-system
    resource_definition:
      spec:
        targetNamespaces:
          - gitlab-system

- name: Create GitLab Subscription
  kubernetes.core.k8s:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: gitlab-operator-kubernetes
    namespace: gitlab-system
    resource_definition:
      spec:
        channel: stable
        name: gitlab-operator-kubernetes
        source: operatorhubio-catalog
        sourceNamespace: olm

- name: Wait until GitLab operator is up
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: gitlab-system
    label_selectors:
      - control-plane=controller-manager
  register: gitlab_pod_list
  until: gitlab_pod_list | json_query('resources[*].status.phase') | unique == ["Running"]
  retries: 12
  delay: 10

- name: Install GitLab
  kubernetes.core.k8s:
    api_version: apps.gitlab.com/v1beta1
    kind: GitLab
    name: gitlab
    namespace: gitlab-system
    resource_definition:
      spec:
        chart:
          version: "{{ gitlab_chart_version }}"
          values:
            global:
              hosts:
                domain: "{{ gitlab_base_domain }}"
              hpa:
                apiVersion: autoscaling/v2
              ingress:
                class: nginx
            nginx-ingress:
              enabled: false
            certmanager:
              install: false
            certmanager-issuer:
              email: admin@skyload.info
