- name: Include deploy tasks
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - metallb.yml
    - olm.yml
    - prometheus.yml
    - prometheus-community.yml
    - nginx.yml
    - cert-manager.yml
    - gitlab.yml
    - grafana.yml
