- name: Add a nginx ingress repository
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Install nginx ingress
  kubernetes.core.helm:
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "{{ nginx_chart_version }}"
    create_namespace: true
    release_name: ingress-nginx
    release_namespace: ingress-nginx
    release_values:
      controller:
        ingressClassResource:
          default: true
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
    wait: true
