- name: Add Prometheus Community chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install Node Exporter
  kubernetes.core.helm:
    chart_ref: prometheus-community/prometheus-node-exporter
    chart_version: "{{ node_exporter_chart_version }}"
    create_namespace: true
    release_name: node-exporter
    release_namespace: prometheus-community
    wait: true
