- name: Complete the first part
  hosts: all
  become: true
  roles:
    - role: common

    - role: geerlingguy.gitlab

    - role: caddy_ansible.caddy_ansible

    - role: prometheus.prometheus.prometheus
    - role: prometheus.prometheus.node_exporter
    - role: prometheus.prometheus.systemd_exporter

    - role: grafana
