- name: Complete the first path
  hosts: all
  become: true
  roles:
    - role: caddy_ansible.caddy_ansible

    - role: geerlingguy.gitlab

    - role: prometheus.prometheus.prometheus
    - role: prometheus.prometheus.node_exporter
    - role: prometheus.prometheus.systemd_exporter
