roles:
  - name: caddy_ansible.caddy_ansible
    version: v3.2.0
  - name: geerlingguy.gitlab
    version: master

collections:
  - name: ansible.posix
    version: 1.5.1
  - name: prometheus.prometheus
    version: 0.5.0
  - name: community.grafana
    version: 1.5.4
